### ISSUE TITLE
Orange3 Text widgets don't show up

### ISSUE THREAD

**Issue by BlankerHans** [biolab/orange3-text#1055]
**Describe the bug**
The installation is succesful as there is no error message.

**To Reproduce**
Options -> Add-ons -> install text

**Expected behavior**
Widgets showing up. I installed different add-ons for example time series and the widgets show up on the left.

**Orange version:**
3.36.2

I am using orange in an anaconda environment.

**Text add-on version:**
1.15.0

**Operating system:**
Ubuntu 20.04

**Comment by BlankerHans** [comment]
Also this is the error within the terminal:

python -m Orange.canvas
2024-05-05 15:24:52,164:ERROR:orangecanvas.registry.discovery: An ImportError occurred while loading entry point 'Text Mining = orangecontrib.text.widgets'
Traceback (most recent call last):
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/orangecanvas/registry/discovery.py", line 134, in run
    point = entry_point.resolve()
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2488, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/orangecontrib/text/__init__.py", line 8, in <module>
    from .corpus import Corpus
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/orangecontrib/text/corpus.py", line 22, in <module>
    from gensim import corpora
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/gensim/__init__.py", line 11, in <module>
    from gensim import parsing, corpora, matutils, interfaces, models, similarities, utils  # noqa:F401
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/gensim/corpora/__init__.py", line 6, in <module>
    from .indexedcorpus import IndexedCorpus  # noqa:F401 must appear before the other classes
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/gensim/corpora/indexedcorpus.py", line 14, in <module>
    from gensim import interfaces, utils
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/gensim/interfaces.py", line 19, in <module>
    from gensim import utils, matutils
  File "/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/gensim/matutils.py", line 20, in <module>
    from scipy.linalg import get_blas_funcs, triu
ImportError: cannot import name 'triu' from 'scipy.linalg' (/home/blankerhans/anaconda3/envs/orange3/lib/python3.10/site-packages/scipy/linalg/__init__.py)

**Comment by psychochemist** [comment]
I have identical issue. Same versions of Orange and add-on. Except I am on Ubuntu 22.04.

**Comment by psychochemist** [comment]
@BlankerHans I have found the following workaround to be working for me  https://stackoverflow.com/questions/78279136/importerror-cannot-import-name-triu-from-scipy-linalg-when-importing-gens?.  After i install this version of Scipy the Orange loads the widgets successfully.

**Comment by BlankerHans** [comment]
Your are king. This actually was the fix also for me. :D

**Comment by BlankerHans** [comment]
pip install scipy==1.10.1

**Comment by markotoplak** [comment]
Duplicete of  #1055
