### ISSUE TITLE
Text 0.2.5 gives error message

### ISSUE THREAD

**Issue by bernardofn** [biolab/orange3-text#307]
##### Text version
0.2.5 

##### Orange version
3.4.1 launched from Anaconda Navigator

##### Expected behavior
Install Text 0.2.5

##### Actual behavior
Gives error message (see text and giff below)

##### Steps to reproduce the behavior
Options -> Add-ons... -> Text -> OK

##### Additional info (worksheets, data, screenshots, ...)
 
**Error message details**

Collecting Orange3-Text
  Using cached Orange3-Text-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\extern\__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
      File "C:\Users\BERNARDO\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\BERNARDO\AppData\Local\Temp\pip-build-7b8389dx\Orange3-Text\

** Giff showing the error message ****
![orange_04](https://user-images.githubusercontent.com/29437665/29160083-3892dff6-7db1-11e7-9ad8-ccda0723ca88.gif)

**Comment by ajdapretnar** [comment]
I see what might be the issue. Your version of Orange is outdated. I don't think you should be using Anaconda Navigator. For Anaconda, you need to set conda-forge as priority channel as described in the instructions.

Text 0.2.5 is not compatible with such an old version of Orange.

**Comment by bernardofn** [comment]
Thanks, Ajda. I did as in the instructions using conda config --add and later tried to install Orange3-Text. It says that Python 3.6, Anaconda Navigator and Orange3-Text are in conflict.

I solved the problem in a Windows PC by unistalling Anaconda, Python and deleting all Orange folders and then installing Orange (classic).

How should I proceed with the MacBooks? They are also reporting the problem even after installing Orange (classic).

Any ideas?

**Comment by kernc** [comment]
As @inejc pointed out in https://github.com/biolab/orange3-imageanalytics/issues/54#issuecomment-321494051, its a bundled setuptools issue. On OS X, Orange installed from bundle, try:
```bash
/Applications/Orange3.app/Contents/MacOS/python -m pip install -U setuptools==35.0.2 pip==9.0.1
```

**Comment by bernardofn** [comment]
Thanks guys! It works well now. 

The typical user to face this problem is the one who was launching Orange through Anaconda Navigator and wanted to update Orange3-Text.

What you should do is uninstall Orange in Anaconda. Then install it from 'bundle'. Then, if you try to install the Text add-on, you'll get the error. 

So run what @kernc suggested, and it works fine! Thanks again.

**Comment by ajdapretnar** [comment]
Can we consider this issue solved and close it?

**Comment by bernardofn** [comment]
Yes, @ajdapretnar! Thanks for the support.
