### ISSUE TITLE
Pickling UDPipe

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#387]
##### Text version

0.5.2

##### Orange version

3.17.dev

##### Expected behavior
One can build a network of tokens with Network from Distances.

##### Actual behavior
Network from Distances fails when using Largest connected component option.

##### Steps to reproduce the behavior
Corpus - Preprocess Text (use UDPipe) - Bag of Words - Distances - Network from Distances (select Largest connected component).

##### Additional info (worksheets, data, screenshots, ...)
At first it seems like a Network add-on issue, but reading the error it seems that Network from Distances tries to pickle a UDPipe.Model object, which I am not sure why it is transmitted so far downstream...

Error text:
Error encountered in widget Network from Distances:

```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/gui.py", line 2318, in __call__
    self.func(**kwds)
  File "/Users/ajda/orange/orange3-network/orangecontrib/network/widgets/OWNxFromDistances.py", line 265, in generateGraph
    self.graph = graph.subgraph(component)
  File "/Users/ajda/orange/orange3-network/orangecontrib/network/network.py", line 167, in subgraph
    G = self.copy()
  File "/Users/ajda/orange/orange3-network/orangecontrib/network/network.py", line 177, in copy
    obj._items = copy.deepcopy(self._items)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 220, in 
    y = [deepcopy(a, memo) for a in x]
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 273, in 
    args = (deepcopy(arg, memo) for arg in args)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/ajda/miniconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle udpipe.Model objects

```

**Comment by ajdapretnar** [comment]
Closed via #447.
