### ISSUE TITLE
Issue with Text Add-In

### ISSUE THREAD

**Issue by SonkMatthias** [biolab/orange3-text#437]
##### Text version

Text 0.6.0

##### Orange version

3.21.0

##### Expected behavior

installing the "text" add-in

##### Actual behavior

i am not able to install the add-in "text" since version 3.17.XX , is that a known issue?

##### Steps to reproduce the behavior

My OS is Win10Pro 

I tried two ways:

first i tried to install Orange via Anaconda 3, but i was not able (not the main issue here).
second  i installed Orange via .exe (Orange3-3.21.0-Miniconda-x86_64; downloaded from http://orange.biolab.si/download/) and tried to install the "text" Add-in via: menu _Options→Add-ons→Orange3-Text

##### Additional info (worksheets, data, screenshots, ...)

![grafik](https://user-images.githubusercontent.com/51823768/59508310-c6f5e180-8ead-11e9-9cb5-e9d828d8c545.png)

```
Show Details....:

Collecting Orange3-Text
Requirement already satisfied: beautifulsoup4 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (4.7.1)
Requirement already satisfied: simhash in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: nltk>=3.0.5 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (3.4.3)
Requirement already satisfied: wikipedia in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: lxml in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (4.3.4)
Requirement already satisfied: numpy in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.14.6)
Collecting ufal.udpipe; platform_system != "Darwin" (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/99/1a/9fbf9658cb3a24bfa2e462b4fda554f48b6fe7a7ee44f5036b1f7d181ca8/ufal.udpipe-1.2.0.2.tar.gz
Requirement already satisfied: biopython in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.73)
Requirement already satisfied: scikit-learn in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (0.20.1)
Requirement already satisfied: odfpy>=1.3.5 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: pdfminer3k>=1.3.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.3.1)
Requirement already satisfied: setuptools-git in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.2)
Requirement already satisfied: scipy in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.1.0)
Requirement already satisfied: gensim>=0.12.3 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (3.7.3)
Requirement already satisfied: docx2txt>=0.6 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (0.7)
Requirement already satisfied: validate-email in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (1.3)
Requirement already satisfied: tweepy in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (3.7.0)
Requirement already satisfied: Orange3>=3.4.3 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3-Text) (3.21.0)
Requirement already satisfied: soupsieve>=1.2 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from beautifulsoup4->Orange3-Text) (1.9.1)
Requirement already satisfied: six in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from nltk>=3.0.5->Orange3-Text) (1.12.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from wikipedia->Orange3-Text) (2.21.0)
Requirement already satisfied: defusedxml in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from odfpy>=1.3.5->Orange3-Text) (0.6.0)
Requirement already satisfied: pytest>=2.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (4.6.3)
Requirement already satisfied: ply>=3.4 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.11)
Requirement already satisfied: smart-open>=1.7.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.8.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from tweepy->Orange3-Text) (1.2.0)
Requirement already satisfied: PySocks>=1.5.7 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from tweepy->Orange3-Text) (1.7.0)
Requirement already satisfied: xlsxwriter in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.1.8)
Requirement already satisfied: AnyQt>=0.0.8 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.0.10)
Requirement already satisfied: chardet>=3.0.2 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (3.0.4)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: xlrd>=0.9.2 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.2.0)
Requirement already satisfied: keyring in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (18.0.0)
Requirement already satisfied: networkx in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.3)
Requirement already satisfied: pip>=9.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (19.1.1)
Requirement already satisfied: bottleneck>=1.0.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (1.2.1)
Requirement already satisfied: openTSNE>=0.3.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.3.2)
Requirement already satisfied: keyrings.alt in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (3.1.1)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (2.2.2)
Requirement already satisfied: python-louvain>=0.13 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.13)
Requirement already satisfied: setuptools>=36.3 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (41.0.1)
Requirement already satisfied: joblib>=0.9.4 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.13.2)
Requirement already satisfied: serverfiles in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.3.0)
Requirement already satisfied: docutils in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from Orange3>=3.4.3->Orange3-Text) (0.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (2019.3.9)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from requests<3.0.0,>=2.0.0->wikipedia->Orange3-Text) (1.24.2)
Requirement already satisfied: importlib-metadata>=0.12 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.18)
Requirement already satisfied: attrs>=17.4.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.1.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.4.1)
Requirement already satisfied: wcwidth in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.1.7)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.3.0)
Requirement already satisfied: py>=1.5.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.8.0)
Requirement already satisfied: packaging in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.0)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.12.0)
Requirement already satisfied: more-itertools>=4.0.0; python_version > "2.7" in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (7.0.0)
Requirement already satisfied: boto>=2.32 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (2.49.0)
Requirement already satisfied: boto3 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.9.168)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text) (3.0.1)
Requirement already satisfied: pywin32; sys_platform == "win32" in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text) (223)
Requirement already satisfied: entrypoints in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from keyring->Orange3>=3.4.3->Orange3-Text) (0.3)
Requirement already satisfied: decorator>=4.3.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from networkx->Orange3>=3.4.3->Orange3-Text) (4.4.0)
Requirement already satisfied: numba>=0.38.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from openTSNE>=0.3.0->Orange3>=3.4.3->Orange3-Text) (0.43.1)
Requirement already satisfied: cycler>=0.10 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.4.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2.8.0)
Requirement already satisfied: pytz in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (2019.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from matplotlib>=2.0.0->Orange3>=3.4.3->Orange3-Text) (1.1.0)
Requirement already satisfied: zipp>=0.5 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from importlib-metadata>=0.12->pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.5.1)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.9.4)
Requirement already satisfied: botocore<1.13.0,>=1.12.168 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (1.12.168)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from boto3->smart-open>=1.7.0->gensim>=0.12.3->Orange3-Text) (0.2.1)
Requirement already satisfied: llvmlite>=0.28.0dev0 in c:\users\m.sonk\appdata\local\orange\lib\site-packages (from numba>=0.38.1->openTSNE>=0.3.0->Orange3>=3.4.3->Orange3-Text) (0.28.0)
Building wheels for collected packages: ufal.udpipe
  Building wheel for ufal.udpipe (setup.py): started
  Building wheel for ufal.udpipe (setup.py): finished with status 'error'
  ERROR: Complete output from command 'C:\Users\m.sonk\AppData\Local\Orange\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MF9F4~1.SON\\AppData\\Local\\Temp\\pip-install-089u24rx\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\MF9F4~1.SON\AppData\Local\Temp\pip-wheel-e1jg10op' --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ufal
  copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
  copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
  running build_ext
  building 'ufal_udpipe' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ufal.udpipe
  Running setup.py clean for ufal.udpipe
Failed to build ufal.udpipe
Installing collected packages: ufal.udpipe, Orange3-Text
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    ERROR: Complete output from command 'C:\Users\m.sonk\AppData\Local\Orange\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MF9F4~1.SON\\AppData\\Local\\Temp\\pip-install-089u24rx\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MF9F4~1.SON\AppData\Local\Temp\pip-record-xr1b1z42\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ufal
    copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
    copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
    running build_ext
    building 'ufal_udpipe' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command "'C:\Users\m.sonk\AppData\Local\Orange\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\MF9F4~1.SON\\AppData\\Local\\Temp\\pip-install-089u24rx\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\MF9F4~1.SON\AppData\Local\Temp\pip-record-xr1b1z42\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\MF9F4~1.SON\AppData\Local\Temp\pip-install-089u24rx\ufal.udpipe\
```

**Comment by JakubMarek93** [comment]
Hi,
I have (probably) the same problem with version of Orange 3.23 and text add-on 0.7.3 or Geo add-on 0.2.4. 
Full issue is described here: [https://stackoverflow.com/questions/58032058/orange-error-during-installing-text-add-on/58145500#58145500].
Maybe will be fixed with this bug [biolab/orange-canvas-core#30].

Thanks for your help!
Jakub

**Comment by JakubMarek93** [comment]
I tried to install Text, Geo, etc. add-on with checked "Install add-ons with conda" in the Settings, but the result is the same :/ @ajdapretnar please, do you know, what to do? I would like to use Orange in my master thesis wich is aimed into sentiment analysis :)

**Comment by ajdapretnar** [comment]
@JakubMarek93 Did you restart Orange after checking the box?
Alternatively, you can open Orange Command Prompt and enter:
`conda install orange3-text`
and
`conda install orange3-geo`
in the command line.

**Comment by JakubMarek93** [comment]
@ajdapretnar Thank you for your help! Of course, I restarted Orange and checkbox is still checked.
As I describe here https://stackoverflow.com/questions/58032058/orange-error-during-installing-text-add-on/58145500#58145500, I tried to use Anaconda Prompt and run command:

`conda install orange3-text`

Result is unsuccessful:
 
(base) C:\Users\Jakub>conda install orange3-text
Traceback (most recent call last):
  File "C:\Users\Jakub\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\common\io.py", line 28, in <module>
    from .._vendor.tqdm import tqdm
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\_vendor\tqdm\__init__.py", line 8, in <module>
    from ._tqdm import tqdm
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\_vendor\tqdm\_tqdm.py", line 13, in <module>
    from ._utils import _supports_unicode, _environ_cols_wrapper, _range, _unich, \
  File "C:\Users\Jakub\Miniconda3\lib\site-packages\conda\_vendor\tqdm\_utils.py", line 31, in <module>
    colorama.init()
AttributeError: module 'colorama' has no attribute 'init' 

I also tried to use another PC with another path of installation. Unfortunately, result is the same.

**Comment by ajdapretnar** [comment]
Well, this seems like your conda is broken. This has nothing to do with Orange - colorama is not one of its dependencies. Probably a re-installation of conda will fix the problem.

**Comment by ajdapretnar** [comment]
Also, Anaconda Prompt is not the same as Orange Command Prompt. Try this one instead as you will activate Orange's virtual environment.

**Comment by JakubMarek93** [comment]
Oh, you are right :)
Re-installation of conda didn´t help. 
I would like to try Orange Command Prompt instead of Anaconda Prompt, but I actually don´t know, how to install some add-on with this tool. I don´t have any experinece with virtual environment.

**Comment by ajdapretnar** [comment]
Fixed via: https://github.com/biolab/orange-canvas-core/commit/a6148850e7d2fd7c0b263e387ba22e370bd8afe4. The new release is already available.
