### ISSUE TITLE
Error - Installing text add on

### ISSUE THREAD

**Issue by AJ072z** [biolab/orange3-text#463]
##### Additional info (worksheets, data, screenshots, ...)

There is an error when i try to install text add on. by defaulf install add ons with conda is checked.  Below is the error details** 

```
Collecting Orange3-Text
  Using cached https://files.pythonhosted.org/packages/2e/1f/aab1241d3a9f67fcba1fdec4709fa2a15ae3522d068a36c7508ba19a0ac1/Orange3_Text-0.7.3-py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (4.8.1)
Requirement already satisfied: biopython in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.74)
Requirement already satisfied: docx2txt>=0.6 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (0.8)
Requirement already satisfied: lxml in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (4.4.1)
Requirement already satisfied: setuptools-git in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.2)
Requirement already satisfied: scipy in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.2.1)
Requirement already satisfied: numpy in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.16.4)
Requirement already satisfied: Orange3<4.0a,>=3.20 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from -c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (3.23.1)
Requirement already satisfied: wikipedia in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: scikit-learn in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (0.21.2)
Requirement already satisfied: tweepy in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (3.8.0)
Requirement already satisfied: nltk>=3.0.5 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (3.4.5)
Requirement already satisfied: simhash in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.9.0)
Requirement already satisfied: pdfminer3k>=1.3.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.3.1)
Collecting ufal.udpipe; platform_system != "Darwin" (from Orange3-Text)
  Using cached https://files.pythonhosted.org/packages/99/1a/9fbf9658cb3a24bfa2e462b4fda554f48b6fe7a7ee44f5036b1f7d181ca8/ufal.udpipe-1.2.0.2.tar.gz
Requirement already satisfied: validate-email in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.3)
Requirement already satisfied: odfpy>=1.3.5 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (1.4.0)
Requirement already satisfied: gensim>=0.12.3 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3-Text) (3.8.1)
Requirement already satisfied: soupsieve>=1.2 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from beautifulsoup4->Orange3-Text) (1.9.4)
Requirement already satisfied: python-louvain>=0.13 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.13)
Requirement already satisfied: keyrings.alt in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (3.1.1)
Requirement already satisfied: orange-canvas-core<0.2a,>=0.1.7 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.1.7)
Requirement already satisfied: setuptools>=36.3 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (41.0.1)
Requirement already satisfied: joblib>=0.9.4 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.13.2)
Requirement already satisfied: AnyQt>=0.0.8 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.0.10)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (3.1.1)
Requirement already satisfied: chardet>=3.0.2 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (3.0.4)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.10.0)
Requirement already satisfied: pip>=9.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (19.2.2)
Requirement already satisfied: serverfiles in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.3.0)
Requirement already satisfied: docutils in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.15.2)
Requirement already satisfied: networkx in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2.3)
Requirement already satisfied: keyring in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (18.0.0)
Requirement already satisfied: openTSNE>=0.3.11 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.3.11)
Requirement already satisfied: xlsxwriter in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (1.1.8)
Requirement already satisfied: xlrd>=0.9.2 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (1.2.0)
Requirement already satisfied: orange-widget-base<4.1a,>=4.0a in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (4.0.1)
Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.25.1)
Requirement already satisfied: bottleneck>=1.0.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (1.2.1)
Requirement already satisfied: requests in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2.22.0)
Requirement already satisfied: pyyaml in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (5.1.2)
Requirement already satisfied: six>=1.10.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from tweepy->Orange3-Text) (1.12.0)
Requirement already satisfied: PySocks>=1.5.7 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from tweepy->Orange3-Text) (1.7.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from tweepy->Orange3-Text) (1.2.0)
Requirement already satisfied: pytest>=2.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (5.2.1)
Requirement already satisfied: ply>=3.4 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pdfminer3k>=1.3.1->Orange3-Text) (3.11)
Requirement already satisfied: defusedxml in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from odfpy>=1.3.5->Orange3-Text) (0.6.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from gensim>=0.12.3->Orange3-Text) (1.8.4)
Requirement already satisfied: commonmark in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.8.1)
Requirement already satisfied: cachecontrol[filecache] in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.12.5)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2.4.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from matplotlib>=2.0.0->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2.8.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from networkx->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (4.4.0)
Requirement already satisfied: entrypoints in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.3)
Requirement already satisfied: pywin32; sys_platform == "win32" in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from keyring->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (223)
Requirement already satisfied: pynndescent>=0.3 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.3.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pandas->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2019.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from requests->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (2.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from requests-oauthlib>=0.7.0->tweepy->Orange3-Text) (3.1.0)
Requirement already satisfied: more-itertools>=4.0.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (7.2.0)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.23)
Requirement already satisfied: wcwidth in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.1.7)
Requirement already satisfied: atomicwrites>=1.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.3.0)
Requirement already satisfied: py>=1.5.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (1.8.0)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.2)
Requirement already satisfied: pluggy<1.0,>=0.12 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.13.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (19.2.0)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.4.1)
Requirement already satisfied: boto3 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (1.9.246)
Requirement already satisfied: boto>=2.32 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (2.49.0)
Requirement already satisfied: future in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from commonmark->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.17.1)
Requirement already satisfied: msgpack in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.6.1)
Requirement already satisfied: lockfile>=0.9 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from cachecontrol[filecache]->orange-canvas-core<0.2a,>=0.1.7->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.12.2)
Requirement already satisfied: numba>=0.39 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.45.1)
Requirement already satisfied: zipp>=0.5 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest>=2.0->pdfminer3k>=1.3.1->Orange3-Text) (0.6.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (0.9.4)
Requirement already satisfied: botocore<1.13.0,>=1.12.246 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (1.12.246)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from boto3->smart-open>=1.8.1->gensim>=0.12.3->Orange3-Text) (0.2.1)
Requirement already satisfied: llvmlite>=0.29.0dev0 in c:\users\lenovo\appdata\local\orangeee\lib\site-packages (from numba>=0.39->pynndescent>=0.3->openTSNE>=0.3.11->Orange3<4.0a,>=3.20->-c C:\Users\LENOVO\AppData\Local\Temp\tmpavj969xy.txt (line 1)) (0.29.0)
Building wheels for collected packages: ufal.udpipe
  Building wheel for ufal.udpipe (setup.py): started
  Building wheel for ufal.udpipe (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\LENOVO\AppData\Local\Orangeee\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LENOVO\AppData\Local\Temp\pip-wheel-ea7jsz70' --python-tag cp36
       cwd: C:\Users\LENOVO\AppData\Local\Temp\pip-install-0t19d7ie\ufal.udpipe\
  Complete output (11 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ufal
  copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
  copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
  running build_ext
  building 'ufal_udpipe' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ufal.udpipe
  Running setup.py clean for ufal.udpipe
Failed to build ufal.udpipe
Installing collected packages: ufal.udpipe, Orange3-Text
  Running setup.py install for ufal.udpipe: started
    Running setup.py install for ufal.udpipe: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\LENOVO\AppData\Local\Orangeee\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-kt39f03j\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\LENOVO\AppData\Local\Temp\pip-install-0t19d7ie\ufal.udpipe\
    Complete output (11 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ufal
    copying ufal\__init__.py -> build\lib.win-amd64-3.6\ufal
    copying ufal\udpipe.py -> build\lib.win-amd64-3.6\ufal
    running build_ext
    building 'ufal_udpipe' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\LENOVO\AppData\Local\Orangeee\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"'; __file__='"'"'C:\\Users\\LENOVO\\AppData\\Local\\Temp\\pip-install-0t19d7ie\\ufal.udpipe\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LENOVO\AppData\Local\Temp\pip-record-kt39f03j\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by robertcv** [comment]
Go to Options -> Settings -> Add-ons and check "install add-ons with conda" and then retry installing the add-on.

**Comment by AJ072z** [comment]
already did that but it didnt work

**Comment by ajdapretnar** [comment]
One options is to re-start Orange.

Alternatively, you need to describe how you installed Orange in the first place as suggested in the issue template.

**Comment by AJ072z** [comment]
Install orange through the link - https://orange.biolab.si/download/#windows  ( Orange3-Miniconda-x86_64.exe (64 bit) 

Python link  - https://docs.conda.io/en/latest/miniconda.html  (python 3.7 windows 64 bit

I've re-started orange also uninstall & install but still cant solve the issue. i really appreciate if you can assist me. thanks

**Comment by ajdapretnar** [comment]
So you installed Orange _and_ Python separately? This should not be necessary, as Orange installs Python on its own. There might be a conflict between the two.
How are you installing the Text add-on?

**Comment by AJ072z** [comment]
options>add ons >orange3-text

**Comment by ajdapretnar** [comment]
Ok, try running:
conda install orange3-text
in the terminal.

**Comment by AJ072z** [comment]
Traceback (most recent call last):
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\LENOVO\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\LENOVO\Miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\LENOVO\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LENOVO\Miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\LENOVO\Miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\LENOVO\Miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\LENOVO\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

**Comment by ajdapretnar** [comment]
I am quite sure it is a broken version of conda. Personally, I would uninstall both Orange and Miniconda from the system and they just install Orange. You will get a Miniconda that is compatible with Orange by default - if you wish to use conda, you will have Anaconda Prompt available.

**Comment by AJ072z** [comment]
Thank you very much. its working fine now. after adjusting also some directory issues, text mining is now working fine. appreciate it!
