### ISSUE TITLE
Preprocess + Heat Map: error with clustering

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#508]
##### Text version

0.9.0

##### Orange version

3.25.0.dev0+be3a9ff

##### Expected behavior
Clustering in Heat Map works.

##### Actual behavior
Clustering without 'Split By' (Split By == None) throws an error.

##### Steps to reproduce the behavior
Corpus - Bag of Words (or Sentiment Analysis, anything that gives you numeric values) - Heat Map. In Heat Map set Split By to None and select Clustering (Rows: Clustering).

##### Additional info (worksheets, data, screenshots, ...)
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 567, in __on_split_rows_activated
    self.set_split_variable(self.row_split_cb.currentData(Qt.EditRole))
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 572, in set_split_variable
    self.update_heatmaps()
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 588, in update_heatmaps
    parts = self.construct_heatmaps(self.data, self.split_by_var)
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 742, in construct_heatmaps
    ordered=self.row_clustering == Clustering.OrderedClustering
  File "/Users/ajda/orange/orange3/Orange/widgets/visualize/owheatmap.py", line 642, in cluster_rows
    subset = data[row.indices]
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/corpus.py", line 428, in __getitem__
    Corpus.retain_preprocessing(self, c, key)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/corpus.py", line 492, in retain_preprocessing
    raise TypeError('Indexing by type {} not supported.'.format(type(key)))
TypeError: Indexing by type <class 'range'> not supported.
```

**Comment by ajdapretnar** [comment]
Yeah, this was fixed in Heat Map I reckon.
