### ISSUE TITLE
error in preprocess text

### ISSUE THREAD

**Issue by tunyunlei** [biolab/orange3-text#514]
**I can't use the preprocess text because of the following error:**
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "c:\programdata\anaconda3\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "c:\programdata\anaconda3\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "D:\soft\orange3-text-stable\orangecontrib\text\widgets\owpreprocess.py", line 595, in __init__
    widget = stage(self)
  File "D:\soft\orange3-text-stable\orangecontrib\text\widgets\owpreprocess.py", line 113, in __init__
    self.setup_method_layout()
  File "D:\soft\orange3-text-stable\orangecontrib\text\widgets\owpreprocess.py", line 483, in setup_method_layout
    self.methods = [method() for method in self.methods[:self.STANFORD]]
  File "D:\soft\orange3-text-stable\orangecontrib\text\widgets\owpreprocess.py", line 483, in <listcomp>
    self.methods = [method() for method in self.methods[:self.STANFORD]]
  File "D:\soft\orange3-text-stable\orangecontrib\text\misc\nltk_data_download.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "D:\soft\orange3-text-stable\orangecontrib\text\tag\pos.py", line 81, in __init__
    super().__init__(tagger, self.name)
  File "D:\soft\orange3-text-stable\orangecontrib\text\tag\pos.py", line 14, in __init__
    self.tag_sents = tagger.tag_sents
AttributeError: 'PunktSentenceTokenizer' object has no attribute 'tag_sents'

**Comment by ajdapretnar** [comment]
Please follow the issue template for reporting issues.
Provide OS, Orange version and other important details related to your problem.

**Comment by ajdapretnar** [comment]
Closed due to lack of information.
