### ISSUE TITLE
Preprocess Widget Error - Widget not Displayed

### ISSUE THREAD

**Issue by shijiantony** [biolab/orange3-text#533]
When the Preprocess Widget from Text Mining is added to the Project screen Error is coming and Widget is not getting displayed

##### Text version
Orange3-Text 0.9.1

##### Orange version
Orange 3.25.0

##### Expected behavior
The Preprocess Widget is added to the Orange main screen

##### Actual behavior
When the Preprocess Widget from Text Mining is added to the main screen Error is coming and Widget is not getting displayed

##### Steps to reproduce the behavior
Drag the Preprocess text widget to the main screen

**Comment by shijiantony** [comment]
![Preprocess](https://user-images.githubusercontent.com/65597035/82701493-58a2cd00-9c81-11ea-9735-ff03a2bb037e.jpg)


Screenshot attached

**Comment by ajdapretnar** [comment]
Please copy and paste the entire error here. Thanks!

**Comment by shijiantony** [comment]
Please find the Error Details copied from Orange Command Prompt below:
===============================================


Traceback (most recent call last):
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 86, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "C:\Orange\lib\site-packages\nltk\data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - 'C:\\Users\\schacko/nltk_data'
    - 'C:\\Orange\\nltk_data'
    - 'C:\\Orange\\share\\nltk_data'
    - 'C:\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 669, in __init__
    widget = stage(self)
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 397, in __init__
    super().__init__(master)
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 114, in __init__
    self.setup_method_layout()
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 194, in setup_method_layout
    self.methods = [method() for method in self.methods]
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 194, in <listcomp>
    self.methods = [method() for method in self.methods]
  File "C:\Orange\lib\site-packages\orangecontrib\text\misc\nltk_data_download.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "C:\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 87, in __init__
    self.language = language
  File "C:\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 100, in language
    x.strip() for x in stopwords.words(self.language.lower()))
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 123, in __getattr__
    self.__load()
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 88, in __load
    raise e
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "C:\Orange\lib\site-packages\nltk\data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - 'C:\\Users\\schacko/nltk_data'
    - 'C:\\Orange\\nltk_data'
    - 'C:\\Orange\\share\\nltk_data'
    - 'C:\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************

---------------------------- LookupError Exception ----------------------------
Traceback (most recent call last):
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 86, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "C:\Orange\lib\site-packages\nltk\data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - 'C:\\Users\\schacko/nltk_data'
    - 'C:\\Orange\\nltk_data'
    - 'C:\\Orange\\share\\nltk_data'
    - 'C:\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 378, in __process_init_queue
    self.ensure_created(node)
  File "C:\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 326, in ensure_created
    self.__add_widget_for_node(node)
  File "C:\Orange\lib\site-packages\orangecanvas\scheme\widgetmanager.py", line 242, in __add_widget_for_node
    w = self.create_widget_for_node(node)
  File "C:\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 296, in create_widget_for_node
    widget = self.create_widget_instance(node)
  File "C:\Orange\lib\site-packages\orangewidget\workflow\widgetsscheme.py", line 409, in create_widget_instance
    widget.__init__()
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 669, in __init__
    widget = stage(self)
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 397, in __init__
    super().__init__(master)
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 114, in __init__
    self.setup_method_layout()
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 194, in setup_method_layout
    self.methods = [method() for method in self.methods]
  File "C:\Orange\lib\site-packages\orangecontrib\text\widgets\owpreprocess.py", line 194, in <listcomp>
    self.methods = [method() for method in self.methods]
  File "C:\Orange\lib\site-packages\orangecontrib\text\misc\nltk_data_download.py", line 55, in wrapper
    return func(*args, **kwargs)
  File "C:\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 87, in __init__
    self.language = language
  File "C:\Orange\lib\site-packages\orangecontrib\text\preprocess\filter.py", line 100, in language
    x.strip() for x in stopwords.words(self.language.lower()))
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 123, in __getattr__
    self.__load()
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 88, in __load
    raise e
  File "C:\Orange\lib\site-packages\nltk\corpus\util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "C:\Orange\lib\site-packages\nltk\data.py", line 701, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - 'C:\\Users\\schacko/nltk_data'
    - 'C:\\Orange\\nltk_data'
    - 'C:\\Orange\\share\\nltk_data'
    - 'C:\\Orange\\lib\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - 'C:\\Users\\schacko\\AppData\\Roaming\\Orange\\nltk_data'
**********************************************************************

-------------------------------------------------------------------------------
DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="Adobe Ming Std L", pointsize=9, pixelsize=12, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Adobe Ming Std L", lfWidth=0, lfHeight=-12) dpi=96
QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="Adobe Myungjo Std M", pointsize=9, pixelsize=12, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Adobe Myungjo Std M", lfWidth=0, lfHeight=-12) dpi=96
QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="Adobe Song Std L", pointsize=9, pixelsize=12, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Adobe Song Std L", lfWidth=0, lfHeight=-12) dpi=96
QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)
DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="Fixedsys", pointsize=9, pixelsize=15, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("Fixedsys", lfWidth=0, lfHeight=-15) dpi=96
DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="ImagoBQ-Bold", pointsize=9, pixelsize=12, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("ImagoBQ-Bold", lfWidth=0, lfHeight=-12) dpi=96

**Comment by shijiantony** [comment]
Dear Ajdapretnar,
Please let me know if there is any update on the issue.
Regards.
Shiji

**Comment by shijiantony** [comment]
Dear Ajdapretnar,
Please let me know if there is any update on the issue.
Regards.
Shiji

**Comment by PrimozGodec** [comment]
I cannot reproduce this error, but it seems that there were some errors downloading data by the nltk package. Can you please try running `python -c "import nltk; nltk.download('stopwords')"  in the same environment that Orange is installed?

**Comment by shijiantony** [comment]
Dear Primož Godec,
I have executed the below command from Orange command prompt and after that there was not error in the "preprocess text" .

python -m nltk.downloader all

===================
Below is the result of the command advised by you

(C:\Orange) C:\Orange>python -c "import nltk; nltk.download('stopwords')"
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\schacko\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

===============

The error has been fixed. Thank you so much for your help.

Regards,
Shiji

**Comment by PrimozGodec** [comment]
Great.
