### ISSUE TITLE
Corpus to Network: widget doesn't show in list

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#555]
**Describe the bug**
Corpus to Network doesn't show in list.

**To Reproduce**
Open Orange.

**Expected behavior**
See the widget.

**Orange version:**
3.26.0

**Text add-on version:**
1.0.0

**Operating system:**
OSX

**Additional context**
```
Traceback (most recent call last):
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/registry/discovery.py", line 273, in iter_widget_descriptions
    distribution=distribution
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/discovery.py", line 61, in widget_description
    desc = widget_desc_from_module(module)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangewidget/workflow/discovery.py", line 45, in widget_desc_from_module
    description = WidgetDescription(**description)
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/registry/description.py", line 401, in __init__
    for o in outputs
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/registry/description.py", line 401, in <listcomp>
    for o in outputs
  File "/Applications/Orange3.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/orangecanvas/registry/description.py", line 287, in normalize_type
    return tuple(map(normalize_type_simple, type_))
TypeError: 'NoneType' object is not iterable
```

**Comment by ajdapretnar** [comment]
The widget is activated when Network add-on is installed. From my knowledge, the widget should appear in the list and notify the user of the missing add-on.
