### ISSUE TITLE
WordCloud crashes

### ISSUE THREAD

**Issue by kernc** [biolab/orange3-text#56]
```text
LookupError                                   Traceback (most recent call last):
  File "/home/user/orange3/Orange/canvas/scheme/widgetsscheme.py", line 722, in process_signals_for_widget
    handler(*args)
  File "/home/user/orange3/textmining/orangecontrib/text/widgets/owwordcloud.py", line 241, in on_corpus_change
    self.corpus_counter = Counter(w for doc in data.tokens for w in doc)
  File "/home/user/orange3/textmining/orangecontrib/text/corpus.py", line 159, in tokens
    self._tokens = p(self.documents)
  File "/home/user/orange3/textmining/orangecontrib/text/preprocess.py", line 128, in __call__
    tokens.append(self.tokenizer(document))
  File "/home/user/venvs/orange3/lib/python3.4/site-packages/nltk-3.1-py3.4.egg/nltk/tokenize/__init__.py", line 104, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/home/user/venvs/orange3/lib/python3.4/site-packages/nltk-3.1-py3.4.egg/nltk/tokenize/__init__.py", line 88, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/home/user/venvs/orange3/lib/python3.4/site-packages/nltk-3.1-py3.4.egg/nltk/data.py", line 796, in load
    opened_resource = _open(resource_url)
  File "/home/user/venvs/orange3/lib/python3.4/site-packages/nltk-3.1-py3.4.egg/nltk/data.py", line 914, in _open
    return find(path_, path + ['']).open()
  File "/home/user/venvs/orange3/lib/python3.4/site-packages/nltk-3.1-py3.4.egg/nltk/data.py", line 636, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource 'tokenizers/punkt/PY3/english.pickle' not found.
  Please use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/user/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

Why does it assume I have/want/need NLTK data? How is this different from the issue raised in https://github.com/biolab/orange3-text/pull/47?

**Comment by nikicc** [comment]
Crap, we forgot about that. You need NLTK data since the default NLTK tokenizer requires it. It differs from #47 since there we have to somehow install system packages. Here we just need to assure that one python script is run after installing a package. We already have this script written for travis 🙈

**Comment by nikicc** [comment]
@kernc can you check if #57 fixes this?
