### ISSUE TITLE
Corpus Viewer Index Error

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#595]
**Describe the bug**
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owcorpusviewer.py", line 143, in set_data
    self.selected_documents = [corpus.titles[0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**To Reproduce**
No idea how. Thought it was related to clicking outside the words in word cloud. Apparently not. I had Corpus + Bag of Words, BoW weights in Word Cloud, selected a word in WC and output it to Corpus Viewer.

**Expected behavior**
No bug, obv.

I am putting this here to remember to reproduce it on Monday. If I won't be able to, I'll close.

**Comment by ajdapretnar** [comment]
I have managed to reproduce this.
Corpus (book-excerpts) - Preprocess Text - Document Embedding - Word Cloud - Corpus Viewer
