### ISSUE TITLE
Topic Modeling: error when shifting between models

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#698]
**Describe the bug**
This is a very rare bug, but it seems like when the model is almost finished computing and the user changes the model, one gets an error.

```
-------------------------- AttributeError Exception ---------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owtopicmodeling.py", line 234, in on_result
    self.Outputs.all_topics.send(self.model.get_all_topics_table())
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/topics/topics.py", line 135, in get_all_topics_table
    all_words = self._topics_words(self.n_words)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/topics/topics.py", line 175, in _topics_words
    x = self.model.show_topics(self.num_topics, num_of_words, formatted=False)
AttributeError: 'NoneType' object has no attribute 'show_topics'
-------------------------------------------------------------------------------
```

**To Reproduce**
1. Corpus
2. Topic Modeling
3. Wait until LSI almost finished, then change to LDA. (this does not always guarantee the error)

**Expected behavior**
No crash.

**Orange version:**
3.30.dev

**Text add-on version:**
1.6.0

**Screenshots**
/

**Operating system:**
OSX

**Additional context**
I know this is nigh impossible to replicate, but putting it here for reference.

**Comment by ajdapretnar** [comment]
Closed because it is nigh impossible to replicate.
