### ISSUE TITLE
In 8df7f  version of Orange3-text bag of word doesn't work

### ISSUE THREAD

**Issue by Fazel94** [biolab/orange3-text#71]
TypeError                                     Traceback (most recent call last):
  File "/home/fazel/dev/venv/pyenv/orange/orange3env/lib/python3.4/site-packages/Orange-3.3.4.dev0+db51d83-py3.4-linux-x86_64.egg/Orange/canvas/scheme/widgetsscheme.py", line 722, in process_signals_for_widget
    handler(*args)
  File "/home/fazel/dev/venv/pyenv/orange/orange3env/lib/python3.4/site-packages/Orange-3.3.4.dev0+db51d83-py3.4-linux-x86_64.egg/Orange/widgets/data/owselectcolumns.py", line 487, in set_data
    self.unconditional_commit()
  File "/home/fazel/dev/venv/pyenv/orange/orange3env/lib/python3.4/site-packages/Orange-3.3.4.dev0+db51d83-py3.4-linux-x86_64.egg/Orange/widgets/data/owselectcolumns.py", line 636, in commit
    newdata = self.data.from_table(domain, self.data)
  File "/home/fazel/dev/venv/pyenv/orange/orange3env/lib/python3.4/site-packages/Orange3_Text-0.1.11-py3.4.egg/orangecontrib/text/corpus.py", line 205, in from_table
    t = super().from_table(domain, source, row_indices)
  File "/home/fazel/dev/venv/pyenv/orange/orange3env/lib/python3.4/site-packages/Orange-3.3.4.dev0+db51d83-py3.4-linux-x86_64.egg/Orange/data/table.py", line 314, in from_table
    n_rows = len(source.X)
  File "/usr/local/lib/python3.4/dist-packages/scipy/sparse/base.py", line 198, in __len__
    raise TypeError("sparse matrix length is ambiguous; use getnnz()"
TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

It give me above error when I push the commit button of Bag of Words.

**Comment by nikicc** [comment]
@Fazel94 which version of Orange do you have? Can you try with version 3.3.6 which was released last Friday. This should already be fixed there. Let us know if this solves your problem.

**Comment by Fazel94** [comment]
I use 3.3.4dev0+db51d83 I cloned it from the official github repo.
Where I can get this new version?
Thank you for your response.

**Comment by kernc** [comment]
You just pull from the repo again. It's seen [some updates](https://github.com/biolab/orange3/compare/db51d83...HEAD).

**Comment by Fazel94** [comment]
It was fix by running "python -m Orange.canvas" that ran the latest version 3.3.7 instead of "orange-canvas" that ran 3.3.4 version. 
Thank you.

**Comment by kernc** [comment]
If you re-run `python setup.py install` or `python setup.py develop`, 3.3.7 should run with `orange-canvas` too.

**Comment by nikicc** [comment]
@Fazel94 great to hear that it works! Can we then close this issue?

**Comment by Fazel94** [comment]
I re-ran "python setup.py install" but it didn't fix the problem.
Anyway, I'm good to go and close the issue.
