### ISSUE TITLE
Semantic Viewer not working

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#778]
**Describe the bug**
Semantic Viewer crashes.

```
------------------------ ClosedResourceError Exception ------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 591, in _on_task_done
    super()._on_task_done(future)
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 547, in _on_task_done
    self.on_exception(ex)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owsemanticviewer.py", line 296, in on_exception
    raise ex
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owsemanticviewer.py", line 83, in run
    results.scores = semantic_search(corpus.documents, words, callback)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/semantic_search.py", line 87, in __call__
    result_ = self._server_communicator.embedd_data(chunks, processed_callback=cb)
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 129, in embedd_data
    embeddings = asyncio.get_event_loop().run_until_complete(
  File "/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 199, in embedd_batch
    await self._cancel_workers(tasks)
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 222, in _cancel_workers
    raise ex
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 219, in _cancel_workers
    await asyncio.gather(*tasks)
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 304, in _send_to_server
    emb = await self._send_request(client, data_bytes, url)
  File "/Users/ajda/orange/orange3/Orange/misc/server_embedder.py", line 349, in _send_request
    response = await client.post(url, headers=headers, data=data)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
    return await self.request(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpx/_transports/default.py", line 281, in handle_async_request
    ) = await self._pool.handle_async_request(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 234, in handle_async_request
    response = await connection.handle_async_request(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_async/connection.py", line 148, in handle_async_request
    return await self.connection.handle_async_request(
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_async/http11.py", line 122, in handle_async_request
    await self._send_request_body(stream, timeout)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_async/http11.py", line 168, in _send_request_body
    await self._send_event(event, timeout)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_async/http11.py", line 180, in _send_event
    await self.socket.write(bytes_to_send, timeout)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 77, in write
    return await self.stream.send(data)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/anyio/streams/tls.py", line 159, in send
    await self._call_sslobject_method(self._ssl_object.write, item)
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/anyio/streams/tls.py", line 125, in _call_sslobject_method
    await self.transport_stream.send(self._write_bio.read())
  File "/Users/ajda/envs/o3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1116, in send
    raise ClosedResourceError
anyio.ClosedResourceError
-------------------------------------------------------------------------------
```

**To Reproduce**
1. Corpus (book-excerpts) as Corpus
2. Word List ("sara", "people", "think") as Words
3. Semantic Viewer

**Expected behavior**
Semantic Viewer works.

**Orange version:**
3.32.dev

**Text add-on version:**
1.7.0dev

**Comment by PrimozGodec** [comment]
As I tested locally (not 100% sure) this one should solve the error: https://github.com/biolab/orange3/pull/5862

**Comment by PrimozGodec** [comment]
https://github.com/biolab/orange3/pull/5862 is merged. @ajdapretnar can you try if it works with the current Orange3 master?

**Comment by ajdapretnar** [comment]
Unfortunately not. :/

**Comment by ajdapretnar** [comment]
Updating to newest httpx helped.
