### ISSUE TITLE
Can't install Orange3 Text Add-ons

### ISSUE THREAD

**Issue by Hueypiing** [biolab/orange3-text#794]
##### Text version

There is issue with internet connection error message 

##### Orange version

3.31.1

##### Actual behavior
Traceback (most recent call last):
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\addons.py", line 695, in <lambda>
    lambda config=config: (config, list_available_versions(config)),
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\orangecanvas\application\addons.py", line 1283, in list_available_versions
    defaults = config.addon_defaults_list()
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\Orange\canvas\config.py", line 162, in addon_defaults_list
    return session.get(OFFICIAL_ADDON_LIST).json()
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HPLIM\AppData\Local\Programs\Orange\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='orange.biolab.si', port=443): Max retries exceeded with url: /addons/list (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1125)')))

**Comment by Hueypiing** [comment]
Hi Ajda

Yes, is running Windows. I clicked on the following “Download Orange 3.31.1” to install the program.

***@***.***

Best regards,
Huey Piing  I  Assistant Manager, Compensation & Benefits  I  City Developments Limited  I  (Regn. No. 196300316Z)
Tel: (65) 68778 441  I  9 Raffles Place, #12-01 Republic Plaza, Singapore 048619  I  www.cdl.com.sg<http://www.cdl.com.sg/>

Confidentiality caution & disclaimer. This message, together with any attachment, is intended only for the use of the individual or entity to which it is addressed, and may contain information that is legally privileged and confidential.  If you are not the intended recipient, please be informed that any dissemination, distribution or copying of this message, or any attachment is strictly prohibited. Kindly note that e-mail communications are not secured, and therefore are susceptible to alteration. City Developments Limited will not accept legal responsibility for the contents of this message. If you have received this message in error, please advise the sender by reply e-mail, and delete the message. Thank you for your co-operation.

**Comment by ajdapretnar** [comment]
And the Text add-on? In the dialogue?

**Comment by ajdapretnar** [comment]
Closed due to inactivity.
