### ISSUE TITLE
Topic Modeling: fails to catch errors

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#808]
**Describe the bug**
There was an error on Windows, which was not reported in the widget nor in the crash window. The only place where it was visible was the log window. 😮

Section of error:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 55: character maps to <undefined>
Call stack:
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\concurrent\futures\thread.py", line 80, in _worker
    work_item.run()
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\text\widgets\owtopicmodeling.py", line 113, in _run
    return model.fit_transform(corpus.copy(), on_progress=callback)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\text\topics\topics.py", line 141, in fit_transform
    self.fit(corpus, **kwargs)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\orangecontrib\text\topics\topics.py", line 94, in fit
    self.model = self.Model(
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\gensim\models\ldamodel.py", line 520, in __init__
    self.update(corpus, chunks_as_numpy=use_numpy)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\gensim\models\ldamodel.py", line 1019, in update
    self.do_mstep(rho(), other, pass_ > 0)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\gensim\models\ldamodel.py", line 1072, in do_mstep
    self.print_topics(5)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\gensim\models\basemodel.py", line 37, in print_topics
    return self.show_topics(num_topics=num_topics, num_words=num_words, log=True)
  File "C:\Users\biolab\AppData\Local\Programs\Orange\lib\site-packages\gensim\models\ldamodel.py", line 1196, in show_topics
    logger.info("topic #%i (%.3f): %s", i, self.alpha[i], topic_)
Message: 'topic #%i (%.3f): %s'
Arguments: (10, 0.05, '0.016*"rebalans_NOUN" + 0.013*"proračun_NOUN" + 0.010*"vrednotenje_NOUN" + 0.010*"nepremičnina_NOUN" + 0.005*"skrivnost_NOUN" + 0.005*"evro_NOUN" + 0.005*"občina_NOUN" + 0.005*"leto_NOUN" + 0.005*"milijon_NOUN" + 0.005*"minister_NOUN"')

```

**To Reproduce**
1. Run Topic Modeling on Slovenian texts. (hopefully this would raise the error)

**Expected behavior**
Error is caught somewhere.

**Orange version:**
3.32.0

**Text add-on version:**
1.6.2

**Screenshots**
/

**Operating system:**
Windows

**Additional context**
/

**Comment by PrimozGodec** [comment]
Could be fixed with: https://github.com/biolab/orange-canvas-core/pull/229

**Comment by ajdapretnar** [comment]
This refers more to the inability of the widget to display errors as it should. Would logging with utf-8 really than raise an error?

**Comment by PrimozGodec** [comment]
Widget display errors if they are raised and come to the widget in this case the error was caught and just printed by the Gensim library and cannot be recognized by the widget. Even topic modelling continued despite the error.

**Comment by PrimozGodec** [comment]
Err
