### ISSUE TITLE
Extract Keywords: multiple crashes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#827]
**Describe the bug**
I managed to crash the widget with multiple crashes.

```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owkeywords.py", line 349, in __on_selection_changed
    self.commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1985, in conditional_commit
    do_commit()
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 1995, in do_commit
    commit()
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owkeywords.py", line 480, in commit
    words = Table.from_list(domain, data)
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 970, in from_list
    vals = [var.to_val(val) for var, val in zip(all_vars, row)]
  File "/Users/ajda/orange/orange3/Orange/data/table.py", line 970, in <listcomp>
    vals = [var.to_val(val) for var, val in zip(all_vars, row)]
  File "/Users/ajda/orange/orange3/Orange/data/variable.py", line 573, in to_val
    return float(s)
ValueError: could not convert string to float: '_can_'
-------------------------------------------------------------------------------
```

```
---------------------------- ValueError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-widget-base/orangewidget/gui.py", line 2784, in paint
    bar_rect.setWidth(max(0, min(int(w * ratio), w)))
ValueError: cannot convert float NaN to integer
-------------------------------------------------------------------------------
```

Finally, segfault.

**To Reproduce**
1. Corpus (book-excerpts)
2. Extract Keywords (let it compute TF-IDF)
3. Select YAKE! and let it start computing
4. While YAKE is still computing, sort the TF-IDF scores.

**Expected behavior**
No crash.

**Orange version:**
3.33.dev

**Text add-on version:**
1.7.0

**Comment by ajdapretnar** [comment]
Correction, the second crash + segfault happens even without trying to sort, just letting YAKE! run on unpreprocessed book-excerpts corpus.
