### ISSUE TITLE
Ontology: adding empty words crashes

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-text#883]
**Describe the bug**
Ontology crashes with:
```
---------------------------- IndexError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owontology.py", line 795, in __on_ontology_data_changed
    self.__update_score()
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owontology.py", line 853, in __update_score
    score = round(self.__onto_handler.score(tree), 2) \
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/ontology.py", line 342, in score
    self._get_embeddings(tree.labels, wrap_callback(callback, end=0.7)),
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/ontology.py", line 366, in _get_embeddings
    embs = self.embedder(missing, callback=wrap_callback(callback, start=0.6, end=0.9))
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/vectorization/sbert.py", line 50, in __call__
    sorted_texts = sorted(
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/vectorization/sbert.py", line 52, in <lambda>
    key=lambda x: len(x[1][0]) if x[1] is not None else 0,
IndexError: string index out of range
-------------------------------------------------------------------------------
```

**To Reproduce**
1. Open Ontology.
2. Click + a couple of times.

**Expected behavior**
No crash.

**Orange version:**
3.32.0

**Text add-on version:**
1.7.0

**Comment by PrimozGodec** [comment]
It was a bug in SBERT script and it is fixed in https://github.com/biolab/orange3-text/pull/930
